/** @type {import('tailwindcss').Config} */

export default {
  darkMode: 'class',
  content: ["./src/**/*.{js,jsx,ts,tsx,vue}",],
  theme: {
    extend: {
      colors: {
        lightBackground: '#fff',
        darkBackground: '#171717',
        lightText: '#111827',
        darkText: '#fff',
        primary: '#111827',
        secondary: '#fff',
        bannerLightBackground: '#f87171',
        bannerDarkBackground: '#f87171',
        bannerLightText: '#06080E',
        bannerDarkText: '#fff',
        navbarLightBackground: '#fff',
        navbarDarkBackground: '#171717',
        navbarLightOffsetBackground: '#f87171',
        navbarDarkOffsetBackground: '#f87171',
        navbarLightText: '#111827',
        navbarDarkText: '#fff',
        heroLightBackground: '#fff',
        heroDarkBackground: '#171717',
        heroLightText: '#27272a',
        heroDarkText: '#27272a',
        pricingLightBackground: '#fff',
        pricingDarkBackground: '#171717',
        pricingLightText: '#333',
        pricingDarkText: '#fff',
        loginLightBackground: '#fff',
        loginDarkBackground: '#171717',
        registerLightBackground: '#fff',
        registerDarkBackground: '#171717',
        testimonialLightBackground: '#fff',
        testimonialDarkBackground: '#171717',
        testimonialLightText: '#171717',
        testimonialDarkText: '#fff',
        faqLightBackground: '#fff',
        faqDarkBackground: '#171717',
        faqLightText: '#111827',
        faqDarkText: '#fff',
        featureLightBackground: '#fff',
        featureDarkBackground: '#171717',
        featureLightText: '#171717',
        featureDarkText: '#fff',
        statsLightBackground: '#fff',
        statsDarkBackground: '#171717',
        statsLightText: '#111827',
        statsDarkText: '#fff',
        footerLightBackground: '#fff',
        footerDarkBackground: '#171717',
        footerLightText: '#111827',
        footerDarkText: '#fff',
      },
      fontFamily: {
        sans: ['ui-sans-serif', 'system-ui'],
        serif: ['ui-serif', 'Georgia'],
        mono: ['ui-monospace', 'SFMono-Regular'],
        display: 'Roboto, ui-serif', // Adds a new `font-display` class
        header: 'Poppins, ui-sans', // Adds a new `font-header` class
        body: ['Roboto'],
      },
      boxShadow: {
        pricing: '3px 4px 5px 0#00000024,inset 3px 4px 5px 0#fff70',
        pricingButton: '2px 1px 2px 0 #1212125c,inset 0-1px 0 0#24a184'
      },
      backgroundImage: {
         'banner-pattern': "linear-gradient(43deg, #4158d0 0, #c850c0 46%, #ffcc70 100%)",
         'fir-tree': "linear-gradient(to right, rgb(16, 185, 129), rgb(6, 78, 59))",
         'powder': "linear-gradient(to right, rgb(221, 214, 254), rgb(251, 207, 232))",
         'rosebud': "linear-gradient(to right, rgb(236, 72, 153), rgb(244, 63, 94))",
         'snowflake': "linear-gradient(to right, rgb(217, 70, 239), rgb(6, 182, 212))"
      },
    },
  },
  plugins: [],
}
