/** @type {import('tailwindcss').Config} */

export default {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        lightBackground: '#fff',
        darkBackground: '#171717',
        lightText: '#111827',
        darkText: '#fff',
        primary: '#111827',
        secondary: '#fff',
        logoLight: '#4c1d95',
        logoDark: '#fff',
        bannerLightBackground: '#4c1d95',
        bannerDarkBackground: '#4c1d95',
        bannerLightText: '#fff',
        bannerDarkText: '#fff',
        navbarLightBackground: '#fff',
        navbarDarkBackground: '#171717',
        navbarLightText: '#111827',
        navbarDarkText: '#fff',
        heroLightBackground: '#fff',
        heroDarkBackground: '#171717',
        heroLightText: '#27272a',
        heroDarkText: '#fff',
        pricingLightBackground: '#fff',
        pricingDarkBackground: '#171717',
        pricingLightText: '#333',
        pricingDarkText: '#fff',
        loginLightBackground: '#fff',
        loginDarkBackground: '#171717',
        registerLightBackground: '#fff',
        registerDarkBackground: '#171717',
        registerLightText: '#111827',
        registerDarkText: '#fff',
        testimonialLightBackground: '#ddd6fe',
        testimonialDarkBackground: '#171717',
        testimonialLightText: '#171717',
        testimonialDarkText: '#fff',
        asSeenOnLightBackground: '#ddd6fe',
        asSeenOnDarkBackground: '#171717',
        asSeenOnLightText: '#171717',
        asSeenOnDarkText: '#fff',
        faqLightBackground: '#fff',
        faqDarkBackground: '#171717',
        faqLightText: '#111827',
        faqDarkText: '#fff',
        featureLightBackground: '#fff',
        featureDarkBackground: '#171717',
        featureLightText: '#171717',
        featureDarkText: '#fff',
        statsLightBackground: '#ddd6fe',
        statsDarkBackground: '#171717',
        statsLightText: '#111827',
        statsDarkText: '#fff',
        footerLightBackground: '#ddd6fe',
        footerDarkBackground: '#171717',
        footerLightText: '#111827',
        footerDarkText: '#fff',
      },
      fontFamily: {
        sans: ['ui-sans-serif', 'system-ui'],
        serif: ['ui-serif', 'Georgia'],
        mono: ['ui-monospace', 'SFMono-Regular'],
        display: 'Roboto, ui-serif', // Adds a new `font-display` class
        header: 'Poppins, ui-sans', // Adds a new `font-header` class
        body: ['Roboto'],
      },
      boxShadow: {
        pricing: '3px 4px 5px 0#00000024,inset 3px 4px 5px 0#fff70',
        pricingButton: '2px 1px 2px 0 #1212125c,inset 0-1px 0 0#24a184',
      },
      backgroundImage: {
        'fir-tree': 'linear-gradient(to right, #10B981, #064E3B)',
        'powder': 'linear-gradient(to right, #DDD6FE, #FBCFE8)',
        'rosebud': 'linear-gradient(to right, #EC48E8, #F43F5E)',
        'snowflake': 'linear-gradient(to right, #D946EF, #06B6D4)',
        'hibiscus': 'linear-gradient(to right, #a855f7, #581c87)',
      },
    },
  },
  plugins: [],
}
